server:
  port: 8081

spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_demo?useUnicode=true&characterEncoding=UTF-8
    username: test
    password: Test@123
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  config: classpath:logback-spring.xml
mybatis:
  mapper-locations: classpath:mapper/*.xml
